# Generated by Django 3.0.3 on 2021-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.CharField(max_length=400)),
            ],
        ),
    ]
