# Generated by Django 3.0.3 on 2021-06-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='incorrect_answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
