# Generated by Django 3.0.3 on 2021-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210610_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
