# Generated by Django 3.0.3 on 2021-06-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210610_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
