# Generated by Django 3.0.3 on 2021-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210615_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
